org.gradle.jvmargs=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED

android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Android 16KB page size support for Android 15+ compatibility
android.experimental.enable16KBPageSizes=true

kotlin.mpp.applyDefaultHierarchyTemplate=false
